-   repo: https://github.com/obarbier/pre-commit-hooks
    rev: master
    hooks:
    -   id: branch-name-convention    
        args: ["-p=^(dev|master|release|((feature|bigfeature|task|bugfix|hotfix)\/([A-Z]|[a-z]|[0-9])+))$"]
        verbose: true