# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: apiServices.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import service as _service
from google.protobuf import service_reflection
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2
from .scalapb import scalapb_pb2 as scalapb_dot_scalapb__pb2
from . import team_pb2 as team__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='apiServices.proto',
  package='fplsupercharge',
  syntax='proto2',
  serialized_options=b'\220\001\001\342?\002\020\001',
  serialized_pb=b'\n\x11\x61piServices.proto\x12\x0e\x66plsupercharge\x1a google/protobuf/descriptor.proto\x1a\x15scalapb/scalapb.proto\x1a\nteam.proto\"]\n\x0cHttpEndpoint\x12\x14\n\x06method\x18\x01 \x01(\t:\x04POST\x12\x0c\n\x04path\x18\x02 \x01(\t\x12)\n\x05since\x18\x03 \x01(\x0b\x32\x1a.fplsupercharge.ApiVersion\"*\n\nApiVersion\x12\r\n\x05major\x18\x01 \x01(\x05\x12\r\n\x05minor\x18\x02 \x01(\x05\"=\n\nRpcOptions\x12/\n\tendpoints\x18\x01 \x03(\x0b\x32\x1c.fplsupercharge.HttpEndpoint\"=\n\tListTeams\x1a\x30\n\x08Response\x12$\n\x05teams\x18\x01 \x01(\x0b\x32\x15.fplsupercharge.Teams2|\n\x0b\x41piServices\x12m\n\tlistTeams\x12\x19.fplsupercharge.ListTeams\x1a\".fplsupercharge.ListTeams.Response\"!\xf2\x86\x19\x1d\n\x1b\n\x03GET\x12\x0e/fpl/listTeams\x1a\x04\x08\x02\x10\x00:I\n\x03rpc\x12\x1e.google.protobuf.MethodOptions\x18\xee\x90\x03 \x01(\x0b\x32\x1a.fplsupercharge.RpcOptionsB\x08\x90\x01\x01\xe2?\x02\x10\x01'
  ,
  dependencies=[google_dot_protobuf_dot_descriptor__pb2.DESCRIPTOR,scalapb_dot_scalapb__pb2.DESCRIPTOR,team__pb2.DESCRIPTOR,])


RPC_FIELD_NUMBER = 51310
rpc = _descriptor.FieldDescriptor(
  name='rpc', full_name='fplsupercharge.rpc', index=0,
  number=51310, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR)


_HTTPENDPOINT = _descriptor.Descriptor(
  name='HttpEndpoint',
  full_name='fplsupercharge.HttpEndpoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='method', full_name='fplsupercharge.HttpEndpoint.method', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=b"POST".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='path', full_name='fplsupercharge.HttpEndpoint.path', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='since', full_name='fplsupercharge.HttpEndpoint.since', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=106,
  serialized_end=199,
)


_APIVERSION = _descriptor.Descriptor(
  name='ApiVersion',
  full_name='fplsupercharge.ApiVersion',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='major', full_name='fplsupercharge.ApiVersion.major', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='minor', full_name='fplsupercharge.ApiVersion.minor', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=201,
  serialized_end=243,
)


_RPCOPTIONS = _descriptor.Descriptor(
  name='RpcOptions',
  full_name='fplsupercharge.RpcOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='endpoints', full_name='fplsupercharge.RpcOptions.endpoints', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=245,
  serialized_end=306,
)


_LISTTEAMS_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='fplsupercharge.ListTeams.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='teams', full_name='fplsupercharge.ListTeams.Response.teams', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=321,
  serialized_end=369,
)

_LISTTEAMS = _descriptor.Descriptor(
  name='ListTeams',
  full_name='fplsupercharge.ListTeams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[_LISTTEAMS_RESPONSE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=308,
  serialized_end=369,
)

_HTTPENDPOINT.fields_by_name['since'].message_type = _APIVERSION
_RPCOPTIONS.fields_by_name['endpoints'].message_type = _HTTPENDPOINT
_LISTTEAMS_RESPONSE.fields_by_name['teams'].message_type = team__pb2._TEAMS
_LISTTEAMS_RESPONSE.containing_type = _LISTTEAMS
DESCRIPTOR.message_types_by_name['HttpEndpoint'] = _HTTPENDPOINT
DESCRIPTOR.message_types_by_name['ApiVersion'] = _APIVERSION
DESCRIPTOR.message_types_by_name['RpcOptions'] = _RPCOPTIONS
DESCRIPTOR.message_types_by_name['ListTeams'] = _LISTTEAMS
DESCRIPTOR.extensions_by_name['rpc'] = rpc
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HttpEndpoint = _reflection.GeneratedProtocolMessageType('HttpEndpoint', (_message.Message,), {
  'DESCRIPTOR' : _HTTPENDPOINT,
  '__module__' : 'apiServices_pb2'
  # @@protoc_insertion_point(class_scope:fplsupercharge.HttpEndpoint)
  })
_sym_db.RegisterMessage(HttpEndpoint)

ApiVersion = _reflection.GeneratedProtocolMessageType('ApiVersion', (_message.Message,), {
  'DESCRIPTOR' : _APIVERSION,
  '__module__' : 'apiServices_pb2'
  # @@protoc_insertion_point(class_scope:fplsupercharge.ApiVersion)
  })
_sym_db.RegisterMessage(ApiVersion)

RpcOptions = _reflection.GeneratedProtocolMessageType('RpcOptions', (_message.Message,), {
  'DESCRIPTOR' : _RPCOPTIONS,
  '__module__' : 'apiServices_pb2'
  # @@protoc_insertion_point(class_scope:fplsupercharge.RpcOptions)
  })
_sym_db.RegisterMessage(RpcOptions)

ListTeams = _reflection.GeneratedProtocolMessageType('ListTeams', (_message.Message,), {

  'Response' : _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
    'DESCRIPTOR' : _LISTTEAMS_RESPONSE,
    '__module__' : 'apiServices_pb2'
    # @@protoc_insertion_point(class_scope:fplsupercharge.ListTeams.Response)
    })
  ,
  'DESCRIPTOR' : _LISTTEAMS,
  '__module__' : 'apiServices_pb2'
  # @@protoc_insertion_point(class_scope:fplsupercharge.ListTeams)
  })
_sym_db.RegisterMessage(ListTeams)
_sym_db.RegisterMessage(ListTeams.Response)

rpc.message_type = _RPCOPTIONS
google_dot_protobuf_dot_descriptor__pb2.MethodOptions.RegisterExtension(rpc)

DESCRIPTOR._options = None

_APISERVICES = _descriptor.ServiceDescriptor(
  name='ApiServices',
  full_name='fplsupercharge.ApiServices',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=371,
  serialized_end=495,
  methods=[
  _descriptor.MethodDescriptor(
    name='listTeams',
    full_name='fplsupercharge.ApiServices.listTeams',
    index=0,
    containing_service=None,
    input_type=_LISTTEAMS,
    output_type=_LISTTEAMS_RESPONSE,
    serialized_options=b'\362\206\031\035\n\033\n\003GET\022\016/fpl/listTeams\032\004\010\002\020\000',
  ),
])
_sym_db.RegisterServiceDescriptor(_APISERVICES)

DESCRIPTOR.services_by_name['ApiServices'] = _APISERVICES

ApiServices = service_reflection.GeneratedServiceType('ApiServices', (_service.Service,), dict(
  DESCRIPTOR = _APISERVICES,
  __module__ = 'apiServices_pb2'
  ))

ApiServices_Stub = service_reflection.GeneratedServiceStubType('ApiServices_Stub', (ApiServices,), dict(
  DESCRIPTOR = _APISERVICES,
  __module__ = 'apiServices_pb2'
  ))


# @@protoc_insertion_point(module_scope)
